name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  publish:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Dependencies
        run: |
          sudo apt install ruby-ffi
          sudo apt install ruby-sqlite3

      - name: Make Schemes
        run: |
          ./build_libvarnam.sh
          ./build_all_schemes.sh

      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: all-schemes
          path: "*.vst"
