name: Publish

on:
  push:
    tags:
      - '*'

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Dependencies
        run: |
          sudo apt install ruby-ffi
          sudo apt install ruby-sqlite3

      - name: Make Schemes
        run: |
          ./build_libvarnam.sh
          ./build_all_schemes.sh

      - name: Upload Release Binary
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: "*.vst"
          file_glob: true
          tag: ${{ github.ref }}
          overwrite: true
